highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://rachelhuls.github.io/vitae
author: Rachel Huls

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Rachel Huls's Resume
name: Rachel Huls
email: rachel.huls@icloud.com
email_full: mailto:rachel.huls@icloud.com
website: github.io/sustain
website_full: https://rachelhuls.github.io/sustain
github: trending
twitter: twitter
tel: +44 0000 000000
tel_full: tel:+440000000000
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
  #street: 44 Perth Street
  postcode: +61853
  city: Mahomet
  country: United States
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
